name: Feature request
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a feature or change?
  - type: textarea
    id: description
    attributes:
      label: What's the feature?
      description: Describe the feature, who it would help, and link to any examples from other apps.
    validations:
      required: true
