name: Deploy '%APPNAME%' App Components to Mainnet

on:
  push:
    branches: [main]

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      deploy-env: "mainnet"
      app-name: "%APPNAME%"
      deploy-account-address: ${{ vars.BOS_DEPLOY_ACCOUNT_ID }} 
      signer-account-address: ${{ vars.BOS_SIGNER_ACCOUNT_ID }}
      signer-public-key: ${{ vars.BOS_SIGNER_PUBLIC_KEY }}
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.BOS_SIGNER_PRIVATE_KEY }}