name: Deploy BOS-Workspace App Components
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        description: "Version of BOS CLI to use for deploy (e.g. 0.3.0)"
        type: string
        default: "0.3.6"
      deploy-env:
        required: false
        description: "Environment to deploy component code to (e.g. mainnet, testnet)"
        type: string
        default: "mainnet"
      app-name:
        required: true
        description: "Workspace app name to deploy (from /apps directory)"
        type: string
      deploy-account-address:
        required: true
        description: "Account under which component code should be deployed"
        type: string
      signer-account-address:
        required: true
        description: "Account which will be used for signing deploy transaction, frequently the same as deploy-account-address"
        type: string
      signer-public-key:
        required: true
        description: "Public key for signing transactions in the format: `ed25519:<public_key>`"
        type: string
      signer-private-key:
        required: true
        description: "Private key in `ed25519:<private_key>` format for signing transaction"
        type: string

jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Deploy Widgets
    env:
      BOS_DEPLOY_ENV: ${{ inputs.deploy-env }}
      BOS_APP_NAME: ${{ inputs.app-name }}
      BOS_DEPLOY_ACCOUNT_ID: ${{ inputs.deploy-account-address }}
      BOS_SIGNER_ACCOUNT_ID: ${{ inputs.signer-account-address }}
      BOS_SIGNER_PUBLIC_KEY: ${{ inputs.signer-public-key }}
      BOS_SIGNER_PRIVATE_KEY: ${{ inputs.signer-private-key }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install bos-cli-rs
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/FroVolod/bos-cli-rs/releases/download/v${{ inputs.cli-version }}/bos-cli-installer.sh | sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install bos-workspace globally
        run: |
          npm install -g bos-workspace

      - name: Build the workspaces
        run: |
          bos-workspace build

      - name: Deploy widgets
        working-directory: ./build/${{ inputs.app-name }}
        run: |
          bos components deploy "$BOS_DEPLOY_ACCOUNT_ID" sign-as "$BOS_SIGNER_ACCOUNT_ID" network-config "$BOS_DEPLOY_ENV" sign-with-plaintext-private-key --signer-public-key "$BOS_SIGNER_PUBLIC_KEY" --signer-private-key "$BOS_SIGNER_PRIVATE_KEY" send
