name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        id: install
        run: yarn install

      - name: Publish to npm
        id: publish
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
