name: Run Tests

on:
    - push

jobs:
    test:
        name: Execute Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn

            - name: Install Dependencies
              id: install
              run: yarn install --frozen-lockfile

            - name: Execute Test Tools
              run: yarn test
